const earlyLife = {
    title: "Early life",
    content: "Dalglish, the son of an engineer, was born in Dalmarnock in the East End of Glasgow, and was brought up in Milton in the north of the city. He moved to the docklands of Govan, near Ibrox, home of Rangers, when he was 15, and he grew up supporting Rangers.<br>Dalglish attended Miltonbank Primary School in Milton and started out as a goalkeeper. He then attended High Possil Senior Secondary School, where he won the inter-schools five-a-side and the inter-year five-a-side competitions. He won the Scottish Cup playing for Glasgow Schoolboys and Glasgow Schools, and was then selected for the Scottish schoolboys team that went undefeated in a Home Nations Victory Shield tournament. In 1966, Dalglish had unsuccessful trials at West Ham and Liverpool."
}

const careerContent = [
    {
        title: "Celtic",
        content: "Dalglish signed a professional contract with Celtic in May 1967. The club's manager Jock Stein sent his assistant Sean Fallon to see Dalglish and his parents at their home, which had Rangers-related pictures on the walls. In his first season Dalglish was loaned out to Cumbernauld United, for whom he scored 37 goals. During this time he also worked as an apprentice joiner. Stein wanted Dalglish to spend a second season on loan at Cumbernauld, but the youngster wanted to turn professional. Dalglish got his wish, and became a regular member of the highly rated Celtic reserve team that became known as the Quality Street Gang, due to it having a large number of future Scottish internationals, including Danny McGrain, George Connelly, Lou Macari, and David Hay. Dalglish made his first-team competitive debut for Celtic in a Scottish League Cup quarter-final tie against Hamilton Academical on 25 September 1968, coming on as a second-half substitute in a 4–2 win."
    },
    {
        title: "Liverpool",
        content: "Dalglish was signed to replace Kevin Keegan, and quickly settled into his new club. He made his debut on 13 August 1977 in the season opener at Wembley, in the 1977 FA Charity Shield against Manchester United. He scored his first goal for Liverpool in his league debut a week later on 20 August, against Middlesbrough. Dalglish also scored three days later on his Anfield debut in a 2–0 victory over Newcastle United, and he scored Liverpool's sixth goal when they beat Keegan's Hamburg 6–0 in the second leg of the 1977 European Super Cup. By the end of his first season with Liverpool, Dalglish had played 62 times and scored 31 goals, including the winning goal in the 1978 European Cup Final at Wembley against Bruges."
    },
    {
        title: "International",
        content: "Tommy Docherty gave Dalglish his debut for the Scottish national side as a substitute in the 1–0 Euro 1972 qualifier victory over Belgium on 10 November 1971 at Pittodrie. Dalglish scored his first goal for Scotland a year later on 15 November 1972 in the 2–0 World Cup qualifier win over Denmark at Hampden Park. Scotland would go on to qualify for the final tournament and he was part of Scotland's 1974 World Cup squad in West Germany. He started in all three games as Scotland was eliminated during the group stages despite not losing any of their three games.\n In 1976, Dalglish scored the winning goal for Scotland at Hampden Park against England, by nutmegging Ray Clemence. A year later Dalglish scored against the same opponents and goalkeeper at Wembley, in another 2–1 win. Dalglish went on to play in both the 1978 World Cup in Argentina where he started in all of Scotland's games – scoring against eventual runners-up the Netherlands in a famous 3–2 win[33] – and the 1982 World Cup in Spain, scoring against New Zealand. On both occasions Scotland failed to get past the group stage. Dalglish was selected for the 22-man squad travelling to Mexico for the 1986 World Cup, but had to withdraw due to injury. In total, Dalglish played 102 times for Scotland (a national record) and he scored 30 goals (also a national record, which matched that set by Denis Law). His final appearance for Scotland, after 15 years as a full international, was on 12 November 1986 at Hampden Park in a Euro 1988 qualifying game against Luxembourg, which Scotland won 3–0.[37] His 30th and final international goal had been two years earlier, on 14 November 1984, in a 3–1 win over Spain in a World Cup qualifier, also at Hampden Park."
    }
]

const managerCarrer = [
    {
        title: "Liverpool",
        content: "After the Heysel Stadium disaster in 1985 and Joe Fagan's subsequent resignation as manager, Dalglish became player-manager of Liverpool. In his first season in charge in 1985–86, he guided the club to its first 'double'. Liverpool achieved this by winning the League Championship by two points over Everton (Dalglish himself scored the winner in a 1–0 victory over Chelsea at Stamford Bridge to secure the title on the final day of the season), and the FA Cup by beating Everton in the final.\nThe 1986–87 season was trophyless for Liverpool. They lost 2–1 to Arsenal in the League Cup final at Wembley. Before the 1987–88 season, Dalglish signed two new players: striker Peter Beardsley from Newcastle and winger John Barnes from Watford. He had already purchased goalscorer John Aldridge from Oxford United (a replacement for Ian Rush, who was moving to Italy) in the spring of 1987 and early into the new campaign, bought Oxford United midfielder Ray Houghton. The new-look Liverpool side shaped by Dalglish topped the league for almost the entire season, and had a run of 37 matches unbeaten in all competitions (including 29 in the league; 22 wins and 7 draws) from the beginning of the season to 21 February 1988, when they lost to Everton in the league. Liverpool were crowned champions with four games left to play, having suffered just two defeats from 40 games. However, Dalglish's side lost the 1988 FA Cup Final to underdogs Wimbledon."
    },
    {
        title: "Hillsborough disaster",
        content: "Dalglish was the manager of Liverpool at the time of the Hillsborough disaster on 15 April 1989. The disaster claimed 94 lives on the day, with the final death toll reaching 96. Dalglish attended many funerals of the victims – including four in one day. and his presence in the aftermath of the disaster has been described as 'colossal and heroic'. Dalglish broke a twenty-year silence about the disaster in March 2009, expressing regret that the police and the FA did not consider delaying the kick-off of the match. During the Hillsborough Memorial Service on 15 April 2011, Liverpool MP Steve Rotheram announced he would submit an Early Day Motion to have Dalglish knighted, 'not only for his outstanding playing and managerial career, but also the charity work he has done with his wife, Marina, for breast cancer support and what he did after Hillsborough. It is common knowledge it affected him deeply'."
    },
    {
        title: "Blackburn Rovers",
        content: "Dalglish returned to management in October 1991, at Second Division Blackburn Rovers who had recently been purchased by multi-millionaire Jack Walker. By the turn of 1992 they were top of the Second Division, and then suffered a dip in form before recovering to qualify for the playoffs, during which Dalglish led Blackburn into the new Premier League by beating Leicester City 1–0 in the Second Division Play-off final at Wembley. The resulting promotion meant that Blackburn were back in the top flight of English football for the first time since 1966. In the 1992 close season, Dalglish signed Southampton's Alan Shearer for a British record fee of £3.5 million.[51] Despite a serious injury which ruled Shearer out for half the season, Dalglish achieved fourth position with the team in the first year of the new Premier League. The following year, Dalglish failed in an attempt to sign Roy Keane. Blackburn finished two positions higher the following season, as runners-up to Manchester United. By this time, Dalglish had added England internationals Tim Flowers and David Batty to his squad."
    },
    {
        title: "Newcastle United",
        content: "In January 1997, Dalglish was appointed manager of Premier League side Newcastle United on a three-and-a-half-year contract, taking over from Kevin Keegan. Dalglish guided the club from fourth position to a runner-up spot in May and a place in the new format of the following season's UEFA Champions League. He then broke up the team which had finished second two years running, selling popular players like Peter Beardsley, Lee Clark, Les Ferdinand and David Ginola and replacing them with ageing stars like John Barnes (34), Ian Rush (36) and Stuart Pearce (35), as well as virtual unknowns like Des Hamilton and Garry Brady. He also made some good long-term signings like Gary Speed and Shay Given. The 1997–98 campaign saw Newcastle finish in only 13th place and, despite Dalglish achieving some notable successes during the season (including a 3–2 UEFA Champions League win over Barcelona and an FA Cup final appearance against Arsenal), he was dismissed by Freddie Shepherd after two draws in the opening two games of the subsequent 1998–99 season, and replaced by former Chelsea manager Ruud Gullit. One commentator from The Independent has since written, 'His 20 months at Newcastle United are the only part of Kenny Dalglish's career that came anywhere near failure'."
    },
    {
        title: "Celtic",
        content: "In June 1999 he was appointed director of football operations at Celtic, with his former Liverpool player John Barnes appointed as head coach. Barnes was dismissed in February 2000 and Dalglish took charge of the first team on an interim basis. He guided them to the Scottish League Cup final, where they beat Aberdeen 2–0 at Hampden Park. Dalglish was dismissed in June 2000, after the appointment of Martin O'Neill as manager. After a brief legal battle, Dalglish accepted a settlement of £600,000 from Celtic."
    },
    {
        title: "Return to Liverpool",
        content: "In April 2009 Liverpool manager Rafael Benítez invited Dalglish to take up a role at the club's youth academy. The appointment was confirmed in July 2009,[63] and Dalglish was also made the club's ambassador.[22] Following Benítez's departure from Liverpool in June 2010, Dalglish was asked to help find a replacement, and in July Fulham's Roy Hodgson was appointed manager.\nA poor run of results at the start of the 2010–11 season led to Liverpool fans calling for Dalglish's return as manager as early as October 2010, and with no subsequent improvement in Liverpool's results up to the end of the year (during which time the club was bought by New England Sports Ventures),[66] Hodgson left Liverpool and Dalglish was appointed caretaker manager on 8 January 2011. Dalglish's first game in charge was on 9 January 2011 at Old Trafford against Manchester United in the 3rd round of the FA Cup, which Liverpool lost 1–0. Dalglish's first league game in charge was against Blackpool on 12 January 2011; Liverpool lost 2–1. After the game, Dalglish admitted that Liverpool faced 'a big challenge'."
    }

]